### Display general info
GET http://localhost:3001/info

### Get All Contacts
GET http://localhost:3001/api/persons


### Get Contact By Id
GET http://localhost:3001/api/persons/2


### Delete Contact By Id
DELETE  http://localhost:3001/api/persons/2


### Create new contact
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Bob Ross",
  "number": "09034735232"
}