### Display general info
GET http://localhost:3001/info

### Get All Contacts
GET http://localhost:3001/api/persons


### Get Contact By Id
GET http://localhost:3001/api/persons/2


### Delete Contact By Id
DELETE  http://localhost:3001/api/persons/2